// frontend/src/App.jsx
import React from 'react';
import { BrowserRouter as Router, Route, Routes, Link } from 'react-router-dom';
import PostListPage from './pages/PostListPage';
import PostDetailPage from './pages/PostDetailPage';
import PostFormPage from './pages/PostFormPage';
import './App.css';

function App() {
  return (
    <Router>
      <div className="min-h-screen bg-gradient-to-br from-gray-50 to-blue-50">
        <div className="container mx-auto p-4">
          <nav className="bg-gray-800 text-white p-4 rounded-md mb-6 shadow-md">
            <ul className="flex space-x-4">
              <li>
                <Link to="/" className="hover:text-gray-300 font-semibold">Home</Link>
              </li>
              <li>
                <Link to="/new-post" className="hover:text-gray-300 font-semibold">New Post</Link>
              </li>
            </ul>
          </nav>
          <Routes>
            <Route path="/" element={<PostListPage />} />
            <Route path="/posts/:id" element={<PostDetailPage />} />
            <Route path="/new-post" element={<PostFormPage />} />
            <Route path="/edit-post/:id" element={<PostFormPage />} />
          </Routes>
        </div>
      </div>
    </Router>
  );
}

export default App;

// vibecodings-vue-frontend/src/App.vue
<template>
  <div id="app" class="bg-gray-100 min-h-screen">
    <nav class="bg-white shadow-md">
      <div class="container mx-auto px-4">
        <div class="flex justify-between items-center py-4">
          <router-link to="/" class="text-2xl font-bold text-gray-800">VibeCodings Blog</router-link>
          <div>
            <router-link to="/" class="text-gray-600 hover:text-gray-800 px-3 py-2">Home</router-link>
            <router-link to="/post/new" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 ml-4">
              New Post
            </router-link>
          </div>
        </div>
      </div>
    </nav>

    <main>
      <RouterView />
    </main>
  </div>
</template>

<script setup lang="ts">
import { RouterLink, RouterView } from 'vue-router';
</script>

<style>
/* 전역 스타일을 여기에 추가할 수 있습니다. */
</style>
